/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#000000",
          "primary-content": "#000000",
          secondary: "#000000",
          "secondary-content": "#000000",
          accent: "#000000",
          "accent-content": "#000000",
          neutral: "#000000",
          "neutral-content": "#FFFFFF",
          "base-100": "#FFFFFF",
          "base-200": "#F5F5F5",
          "base-300": "#E5E5E5",
          "base-content": "#000000",
          info: "#000000",
          success: "#000000",
          warning: "#000000",
          error: "#000000",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#FFFFFF",
          "primary-content": "#FFFFFF",
          secondary: "#FFFFFF",
          "secondary-content": "#FFFFFF",
          accent: "#FFFFFF",
          "accent-content": "#FFFFFF",
          neutral: "#FFFFFF",
          "neutral-content": "#000000",
          "base-100": "#000000",
          "base-200": "#1A1A1A",
          "base-300": "#262626",
          "base-content": "#FFFFFF",
          info: "#FFFFFF",
          success: "#FFFFFF",
          warning: "#FFFFFF",
          error: "#FFFFFF",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
